---
title: "2.0 R lab"
author: "Yijun Shen"
date: "4/11/2022"
output: html_document
---

```{r }
x <- c(1,2,3,4)
x
length(x)# how many vectors included
ls()#check all the data we used
rm()#delete any data that we dont want, add list=ls() to remove all
```

matrix:

```{r }
?matrix
x = matrix(data=c(1,2,3,4), nrow=2, ncol=2)
x
x = matrix(data=c(1,2,3,4), 2,2,byrow=TRUE)#fill the row first before column
x
```

create randomize sample:

```{r }
x = rnorm(50)# randomly 50 variables with mean =0 and sd = 1
x 
y = x + rnorm(50, mean=50, sd=0.1)# alter mean and sd
y
cor(x,y)#correlation function
#can set seed here to ensure getting the same result
```

Graph:
```{r}
plot(x, y, xlab="1", ylab="@", main ="title")
#pdf funcrion
pdf('figure.pdf')
plot(x,y,col='green')
dev.off()#indicate r that we done creating the plot
```

create a sequence of numbers
```{r}
x = seq(1, 10)#vector of integers bw 1 and 10: equally spaced
x
x = 1:10# same thing
seq(0,1,length=10)
x=seq(-pi, pi, length=50)
x
```

other plot:
contour:#a graphical technique for representing a 3-dimensional surface by plotting constant z slices, called contours, on a 2-dimensional format
```{r}
y=x
f = outer(x,y,function(x,y)cos(y)/(1+x^2))# create a function based on x and y
f
contour(x,y,f)#plot regarding x, y and f

contour(x,y,f,nlevels=45, add=T)

fa=(f-t(f))/2
contour(x,y,fa, nlevels=15)
```

image:
```{r}
image(x,y,fa)#contour with color
persp(x,y,fa)# 3d
persp(x,y,fa, theta=40)# theta change the different side horizontally
persp(x,y,fa, theta=30)
persp(x,y,fa, theta=30, phi = 20)
persp(x,y,fa, theta=30, phi = 70)# phi change side vertically
persp(x,y,fa, theta=30, phi = 40)
persp(x,y,fa, theta=30, phi = -40)
```

index data:
```{r}
A = matrix(1:16, 4, 4)
A
A[2,3]#row 2 column 3: in [], first always refer to the row while second refer to the column
A[c(1,3), c(2,4)]#select row 1 and row 3 with column 2 and column 4
A[c(1:3), c(2:4)]
A[c(1:3), c(2:4)]
A[1:3, ]#row1:3 and all column
A[-c(1,3),]#everything without row 1 and row 3
dim(A)#number of row and columns in A
```

Loading Data:
```{r}
fix()# with data name, view dataset as a spreadsheet
na.omit()# with data name, delete the na variables
```

more graph:
```{r}
pairs()#with data naume, creates a scatterplot matrix
```
